// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtlxDml3jZxrMnOR4zcqeU4mpXsDAbzjs',
    appId: '1:431776087961:web:0d35b999b6d84b4ad6dd08',
    messagingSenderId: '431776087961',
    projectId: 'exam-adv',
    authDomain: 'exam-adv.firebaseapp.com',
    storageBucket: 'exam-adv.appspot.com',
    measurementId: 'G-6S9GV1JJGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1PF5NR3T9FkPtMw4_C3SUbzLwQAB6NqM',
    appId: '1:431776087961:android:30e57f056ed37aead6dd08',
    messagingSenderId: '431776087961',
    projectId: 'exam-adv',
    storageBucket: 'exam-adv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAne2u9f-cQ5jg43892BDjRof2P9XtZZFs',
    appId: '1:431776087961:ios:c3a10e598ba397ebd6dd08',
    messagingSenderId: '431776087961',
    projectId: 'exam-adv',
    storageBucket: 'exam-adv.appspot.com',
    iosBundleId: 'com.example.examAdvFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAne2u9f-cQ5jg43892BDjRof2P9XtZZFs',
    appId: '1:431776087961:ios:c3a10e598ba397ebd6dd08',
    messagingSenderId: '431776087961',
    projectId: 'exam-adv',
    storageBucket: 'exam-adv.appspot.com',
    iosBundleId: 'com.example.examAdvFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtlxDml3jZxrMnOR4zcqeU4mpXsDAbzjs',
    appId: '1:431776087961:web:e81bb6376d87234fd6dd08',
    messagingSenderId: '431776087961',
    projectId: 'exam-adv',
    authDomain: 'exam-adv.firebaseapp.com',
    storageBucket: 'exam-adv.appspot.com',
    measurementId: 'G-E42VLLPEPE',
  );
}
